name: auslan_dictionary
description: Free video dictionary of Auslan signs

publish_to: 'none'

version: 1.19.9+827

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus:
  dictionarylib:
    # path: ../dictionarylib
    git:
      url: https://github.com/banool/dictionarylib.git
      ref: main
  dolphinsr_dart:
    git:
      url: https://github.com/banool/dolphhinsr_dart.git
      ref: master
  dots_indicator:
  flutter_native_splash:
  go_router:
  http:
  shared_preferences:
  settings_ui:
  url_launcher:
  media_kit:

dev_dependencies:
  dependency_validator:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/02-okay-512.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/01-okay.png"

flutter:
  uses-material-design: true
