name: auslan_dictionary
description: Free video dictionary of Auslan signs

publish_to: 'none'

version: 1.18.3+800

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider:
  collection:
  cupertino_icons:
  device_info_plus: 11.1.0
  dictionarylib:
    # path: ../dictionarylib
    git:
      url: https://github.com/banool/dictionarylib.git
      ref: main
  dolphinsr_dart:
    git:
      url: https://github.com/banool/dolphhinsr_dart.git
      ref: master
  dots_indicator:
  edit_distance: ^0.5.0-nullsafety.0
  flutter_cache_manager:
  flutter_native_splash:
  go_router:
  http:
  launch_review:
  mailto:
  package_info_plus:
  path_provider:
  shared_preferences:
  settings_ui:
  url_launcher:
  video_player:
  video_player_win:

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/02-okay-512.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/01-okay.png"

flutter:
  uses-material-design: true
