name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.21.0-9.2.pre'
        channel: beta
    
    # Initial build and test
    - run: flutter pub get
    - run: flutter test
    
    #  Build iOS and Android
    - run: flutter build ios --release --no-codesign
    - run: flutter build appbundle
    
    # Publish iOS
    - name: Upload iOS build to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with: 
        app-path: build/ios/iphoneos/Runner.app 
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

    # Publish Android
    - name: Sign release
      id: sign_release
      uses: r0adkll/sign-android-release@v1
      with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}       
          keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Publish build to internal track
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.banool.auslan_dictionary
        # releaseFile: ${{ steps.run_tests.outputs.signedReleaseFile }} 
        releaseFile: build/app/outputs/bundle/release/app-release.aab
        track: internal

